baseurl = "https://dreamy-bartik-1e70e6.netlify.com/"
languageCode = "en-us"
title = "BST 680: Introduction to R"
theme = "material"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Byron C. Jaeger"
  bio = ""
  job = "Assistant Professor of Biostatistics"
  location = "University of Alabama at Birmingham"
  gravatarEmail = "bcjaeger@uab.edu"
  twitter = "byron_jaeger"

# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "syllabus"
  name = "Syllabus"
  pre = "<i class=\"material-icons\">date_range</i>"
  url = "/syllabus"
[[menu.main]]
  weight = 3
  identifier = "policies"
  name = "Policies"
  pre = "<i class=\"material-icons\">gavel</i>"
  url = "/policies"
[[menu.main]]
  weight = 4
  identifier = "rstudio"
  name = "RStudio"
  pre = "<i class=\"material-icons\">cloud_queue</i>"
  url = "https://rstudio.cloud"
[[menu.main]]
  weight = 5
  identifier = "github"
  name = "GitHub"
  pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/UAB-BST-680"
[[menu.main]]
  weight = 6
  identifier = "help"
  name = "Help"
  pre = "<i class=\"material-icons\">help</i>"
  url = "https://github.com/Sta199-S18/community/issues"

[[menu.footer]]
  weight = 1
  identifier = "UAB"
  name = "University of Alabama at Birmingham"
  pre = "<i class=\"button-icon fa fa-2x fa-map-marker\"></i>"
  url = "https://www.soph.uab.edu/bst"
[[menu.footer]]
  weight = 2
  name = "RStudio"
  pre = "<i class=\"icon-rlogo\" style=\"font-size:150%\"></i>"
  url = "https://rstudio.cloud/"
[[menu.footer]]
  weight = 3
  identifier = "GitHub"
  name = "GitHub"
  pre = "<i class=\"button-icon fa fa-2x fa-github\"></i>"
  url = "https://github.com/UAB-BST-680"
[[menu.footer]]

[params]
  dateFormat = "January 2, 2006"
  background = "images/environmental-data-science-r4ds.png"
  favicon = "img/favicon.ico"



